version: '3.8'

services:
  mysql:
    image: mysql:5.7  # 使用輕量化的 MySQL 5.7 映像
    container_name: canchu_mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # 將 MySQL 資料持久化到本機
    environment:
      - MYSQL_DATABASE=canchu  # 替换为您希望的数据库名
      - MYSQL_ROOT_PASSWORD=@gG01020304  # 替换为您希望的root用户密码
      - MYSQL_USER=gemii0606  # 替换为您希望的新用户名
      - MYSQL_PASSWORD=@gG01020304  # 替换为您希望的新用户密码
    networks:
      - canchu_network

  redis:
    image: redis:6.2-alpine  # 使用輕量化的 Redis 6.2 映像
    container_name: canchu_redis
    ports:
      - "6379:6379"
    networks:
      - canchu_network

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./private/combined.crt:/etc/nginx/combined.crt:ro
      - ./private/private.key:/etc/nginx/private.key:ro
    depends_on:
      - canchu
    networks:
      - canchu_network

  canchu:
    build: .  # 使用 Canchu 映像，並將其替換為實際映像名稱
    container_name: canchu
    environment:
      SQL_NODEJS_PW: '@gG01020304'
      DATABASE: canchu
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    command: sh -c "while ! nc -z canchu_mysql 3306; do sleep 1; done && node app.js"
    networks:
      - canchu_network

networks:
  canchu_network:

volumes:
  mysql_data:  # 定義 MySQL 資料持久化的卷