version: '3.8'

services:
  mysql:
    image: mysql:5.7  # 使用輕量化的 MySQL 5.7 映像
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # 將 MySQL 資料持久化到本機

  redis:
    image: redis:6.2-alpine  # 使用輕量化的 Redis 6.2 映像
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # 將 Redis 資料持久化到本機

  canchu:
    build: .  # 使用 Canchu 映像，並將其替換為實際映像名稱
    environment:
      SQL_NODEJS_PW: '@gG01020304'
      DATABASE: canchu
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    networks:
      - canchu_network

  # nginx:
  #   image: nginx:alpine  # 使用輕量化的 Nginx 映像
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./path/to/your/nginx_conf:/etc/nginx/conf.d
  #   depends_on:
  #     - canchu
  #   networks:
  #     - canchu_network

networks:
  canchu_network:

volumes:
  mysql_data:  # 定義 MySQL 資料持久化的卷
  redis_data:  # 定義 Redis 資料持久化的卷