name: Canchu

on: 
 push:
   branches:
     - master
 workflow_dispatch:

permissions:
  contents: write

jobs:    
  test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Build docker compose for test
       run: |
         cd api/1.0
         echo "${{ secrets.ENV_FILE  }}" > .env
         mkdir private
         echo "${{ secrets.PRIVATE_KEY }}" > private/private.key
         echo "${{ secrets.COMBINED_CRT }}" > private/combined.crt
         docker-compose up --build -d
     - name: Wait for containers to start
       run: sleep 20
     - name: Run test file
       run: |
         pwd
         ls
         docker ps -a
         docker exec canchu npm test -- --watch=false --forceExit
         
