name: Canchu

on: 
 push:
   branches:
     - master
 workflow_dispatch:

permissions:
  contents: write

jobs:    
  test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: test
       run: |
         docker-compose up --build -d
         
