name: Canchu

on: 
 push:
   branches:
     - master
 workflow_dispatch:

permissions:
  contents: write

jobs:    
  test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: test
       run: |
         cd api/1.0
         echo "${{ secrets.ENV_FILE  }}" > .env
         docker-compose up --build -d
         docker exec canchu-server npm test -- --watch=false --forceExit
         
