name: Canchu

on: 
 push:
   branches:
     - main
 workflow_dispatch:

permissions:
  contents: write

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
     - name: docker-compose build
       run: |
        docker-compose up --build
